const activity2 = {
  cycles: [
    {
      name: 'Gallina',
      title: 'la gallina',
      image: 'images/Lab2/lab02-card-gallina.svg',
      imageFeedback: 'images/Lab2/lab02-card-gallina.svg',
      feedback: "Sabías que los pollitos se convierten en gallina entre los 4 y 6 meses de edad, a partir de ese momento pueden poner huevos.",
      code: 'gallina',
      cycle: [
        {
          step: 1,
          name: 'Nace',
          code: 'ga-1',
          image: 'images/Lab2/lab02-_gallina1.svg',
        },
        {
          step: 3,
          name: 'Se reproduce',
          code: 'ga-3',
          image: 'images/Lab2/lab02-_gallina3.svg',
        },
        {
          step: 4,
          name: 'Muere',
          code: 'ga-4 ',
          image: 'images/Lab2/lab02-_gallina4.svg',
        },
        {
          step: 2,
          name: 'Crece y se desarrolla',
          code: 'ga-2',
          image: 'images/Lab2/lab02-_gallina2.svg',
        },
      ],
    },
    {
      name: 'Mariposa',
      title: 'la mariposa',
      image: 'images/Lab2/lab02-card-mariposa.svg',
      imageFeedback: 'images/Lab2/lab02-card-mariposa.svg',
      feedback: "Sabías que la mariposa Morpho Azul vive un poco menos de 4 meses, 115 días aproximadamente. ",
      code: 'mariposa',
      cycle: [
                {
          step: 2,
          name: 'Crece y se desarrolla',
          code: 'ma-2',
          image: 'images/Lab2/lab02-_mariposa2.svg',
        },
        {
          step: 3,
          name: 'Se reproduce',
          code: 'ma-4 ',
          image: 'images/Lab2/lab02-_mariposa3.svg',
        },
        {
          step: 1,
          name: 'Nace',
          code: 'ma-1',
          image: 'images/Lab2/lab02-_mariposa1.svg',
        },
        {
          step: 4,
          name: 'Muere',
          code: 'ma-5 ',
          image: 'images/Lab2/lab02-_mariposa4.svg',
        },
      ],
    },
    {
      name: 'Ratón',
      title: 'un ratón',
      image: 'images/Lab2/lab02-card-raton.svg',
      imageFeedback: 'images/Lab2/lab02-card-raton.svg',
      feedback: "Desde las seis semanas de vida, los ratones empiezan a reproducirse, y pueden llegar a tener hasta seis camadas de crías por año. ",
      code: 'raton',
      cycle: [
        {
          step: 3,
          name: 'Se reproduce',
          code: 'ma-3 ',
          image: 'images/Lab2/lab02-_raton3.svg',
        },
        {
          step: 2,
          name: 'Crece y se desarrolla',
          code: 'ra-2',
          image: 'images/Lab2/lab02-_raton2.svg',
        },
        {
          step: 4,
          name: 'Muere',
          code: 'ra-4 ',
          image: 'images/Lab2/lab02-_raton4.svg',
        },
        {
          step: 1,
          name: 'Nace',
          code: 'ra-1',
          image: 'images/Lab2/lab02-_raton1.svg',
        },
      ],
    },
    {
      name: 'Arbol',
      title: 'un árbol de naranja',
      image: 'images/Lab2/lab02-card-arbol.svg',
      imageFeedback: 'images/Lab2/lab02-card-arbol.svg',
      feedback: "Sabías que los árboles que nacen de una semilla toman hasta 10 años para dar fruto.",
      code: 'arbol',
      cycle: [
        {
          step: 2,
          name: 'Crece y se desarrolla',
          code: 'ar-2',
          image: 'images/Lab2/lab02-_arbol2.svg',
        },
        {
          step: 1,
          name: 'Nace',
          code: 'ar-1',
          image: 'images/Lab2/lab02-_arbol1.svg',
        },
        {
          step: 4,
          name: 'Muere',
          code: 'ar-4 ',
          image: 'images/Lab2/lab02-_arbol4.svg',
        },
        {
          step: 3,
          name: 'Se reproduce',
          code: 'ar-3 ',
          image: 'images/Lab2/lab02-_arbol3.svg',
        },
      ],
    },
  ],
}